name: "Cron Job"

on:
  schedule:
    - cron: "*/60 11 * * *"

jobs:
  cronjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Running the cron job
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node .github/workflows/cronjob.js
